# Generated by Django 3.2.7 on 2023-10-16 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='Train',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='topic',
            new_name='train',
        ),
    ]
