# Generated by Django 3.2.7 on 2023-10-16 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20231016_1940'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job',
            new_name='Room',
        ),
        migrations.RenameModel(
            old_name='JobStatus',
            new_name='RoomStatus',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='job',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='job',
            new_name='room',
        ),
    ]
