# Generated by Django 3.2.7 on 2023-10-16 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20231016_2005'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='TransactionKarma',
        ),
    ]
